### ISSUE TITLE
Server failing to start

### ISSUE THREAD

**Issue by ChristopherHaws** [NucleoidMC/Server-Translations#38]
Hello,

My server is failing to start with this mod installed. The error I am getting is:

```
[12:09:14] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'server_translations'!
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:63) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:61) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.1-beta.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.17.1-beta.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) [quilt-loader-0.17.1-beta.6.jar:?]
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class fr.catcore.server.translations.api.ServerTranslations
		at java.lang.Class.forName0(Native Method) ~[?:?]
		at java.lang.Class.forName(Unknown Source) ~[?:?]
		at org.quiltmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:49) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:112) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.entrypoint.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:220) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:51) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:46) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
		at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
		at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
		at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.1-beta.6.jar:?]
		at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.1-beta.6.jar:?]
		at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.17.1-beta.6.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
		at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
		at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:63) [quilt-loader-0.17.1-beta.6.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at fr.catcore.server.translations.TranslationGatherer.init(TranslationGatherer.java:45) ~[Server-Translations-1.4.16+1.19.jar:?]
	at fr.catcore.server.translations.ServerTranslationsInitializer.onInitialize(ServerTranslationsInitializer.java:18) ~[Server-Translations-1.4.16+1.19.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2477 failed
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:248) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.TranslationGatherer.init(TranslationGatherer.java:45) ~[Server-Translations-1.4.16+1.19.jar:?]
	at fr.catcore.server.translations.ServerTranslationsInitializer.onInitialize(ServerTranslationsInitializer.java:18) ~[Server-Translations-1.4.16+1.19.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.TranslationGatherer.init(TranslationGatherer.java:45) ~[Server-Translations-1.4.16+1.19.jar:?]
	at fr.catcore.server.translations.ServerTranslationsInitializer.onInitialize(ServerTranslationsInitializer.java:18) ~[Server-Translations-1.4.16+1.19.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for d4f.mixins.json:LanguageMixin during activity: [Transform -> Method lambda$create$0(Ljava/util/function/BiConsumer;Lnet/fabricmc/loader/api/ModContainer;)V -> INVOKEINTERFACE -> net/fabricmc/loader/impl/metadata/LoaderModMetadata::getEntrypoints:(Ljava/lang/String;)Ljava/util/List;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.TranslationGatherer.init(TranslationGatherer.java:45) ~[Server-Translations-1.4.16+1.19.jar:?]
	at fr.catcore.server.translations.ServerTranslationsInitializer.onInitialize(ServerTranslationsInitializer.java:18) ~[Server-Translations-1.4.16+1.19.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.metadata.LoaderModMetadata
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.TranslationGatherer.init(TranslationGatherer.java:45) ~[Server-Translations-1.4.16+1.19.jar:?]
	at fr.catcore.server.translations.ServerTranslationsInitializer.onInitialize(ServerTranslationsInitializer.java:18) ~[Server-Translations-1.4.16+1.19.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.metadata.LoaderModMetadata
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:243) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:146) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fr.catcore.server.translations.api.resource.language.LanguageReader.loadVanillaTranslations(LanguageReader.java:48) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.reload(ServerTranslations.java:72) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<init>(ServerTranslations.java:51) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.api.ServerTranslations.<clinit>(ServerTranslations.java:33) ~[server-translations-api-1.4.16+1.19.jar-e1bed2a1-0075-42ef-81de-218676ef2d3b-nested.jar:?]
	at fr.catcore.server.translations.TranslationGatherer.init(TranslationGatherer.java:45) ~[Server-Translations-1.4.16+1.19.jar:?]
	at fr.catcore.server.translations.ServerTranslationsInitializer.onInitialize(ServerTranslationsInitializer.java:18) ~[Server-Translations-1.4.16+1.19.jar:?]
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:62) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:33) ~[quilt-loader-0.17.1-beta.6.jar:?]
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:59) ~[quilt-loader-0.17.1-beta.6.jar:?]

	... 16 more
```

**Comment by Patbox** [comment]
Cound you try removing `Discord4Fabric` mod and test again? I seems that it's mixin breaks. If thats the case you should report that to them
